<?php

namespace ContainerVxDID9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DGgJxovService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DGgJxov' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DGgJxov'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'voucher' => ['privates', '.errored..service_locator.DGgJxov.App\\Entity\\reissuevoucher\\Voucher_reissue', NULL, 'Cannot autowire service ".service_locator.DGgJxov": it references class "App\\Entity\\reissuevoucher\\Voucher_reissue" but no such service exists.'],
        ], [
            'voucher' => 'App\\Entity\\reissuevoucher\\Voucher_reissue',
        ]);
    }
}
