<?php

namespace ContainerVxDID9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoucherReissue2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DGgJxov.App\Entity\reissuevoucher\Voucher_reissue' shared service.
     *
     * @return \App\Entity\reissuevoucher\Voucher_reissue
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DGgJxov": it references class "App\\Entity\\reissuevoucher\\Voucher_reissue" but no such service exists.');
    }
}
