<?php

namespace ContainerMuua5Od;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PJUCJBwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pJUCJBw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pJUCJBw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\trainingvideos\\CategoryRepository', 'getCategoryRepositoryService', true],
            'videoRepository' => ['privates', 'App\\Repository\\trainingvideos\\VideoRepository', 'getVideoRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\trainingvideos\\CategoryRepository',
            'videoRepository' => 'App\\Repository\\trainingvideos\\VideoRepository',
        ]);
    }
}
