<?php

namespace ContainerMuua5Od;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.egcZKKl.App\Entity\trainingvideos\Video' shared service.
     *
     * @return \App\Entity\trainingvideos\Video
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.egcZKKl": it references class "App\\Entity\\trainingvideos\\Video" but no such service exists.');
    }
}
