<?php

namespace ContainerZLABvoN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TEH_LMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._TEH.LM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._TEH.LM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\trainingvideos\\CategoryRepository', 'getCategoryRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'videoRepository' => ['privates', 'App\\Repository\\trainingvideos\\VideoRepository', 'getVideoRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\trainingvideos\\CategoryRepository',
            'entityManager' => '?',
            'videoRepository' => 'App\\Repository\\trainingvideos\\VideoRepository',
        ]);
    }
}
