<?php

namespace ContainerZLABvoN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QhJ5uJHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qhJ5uJH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qhJ5uJH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'voucherRepository' => ['privates', 'App\\Repository\\reissuevoucher\\VoucherRepository', 'getVoucherRepositoryService', true],
        ], [
            'voucherRepository' => 'App\\Repository\\reissuevoucher\\VoucherRepository',
        ]);
    }
}
