<?php

namespace ContainerZLABvoN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoucher2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jqd_se5.App\Entity\reissuevoucher\Voucher' shared service.
     *
     * @return \App\Entity\reissuevoucher\Voucher
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Jqd_se5": it references class "App\\Entity\\reissuevoucher\\Voucher" but no such service exists.');
    }
}
