<?php

namespace Container0TVwF8T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JqdSe5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jqd_se5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jqd_se5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'voucher' => ['privates', '.errored..service_locator.Jqd_se5.App\\Entity\\reissuevoucher\\Voucher', NULL, 'Cannot autowire service ".service_locator.Jqd_se5": it references class "App\\Entity\\reissuevoucher\\Voucher" but no such service exists.'],
        ], [
            'voucher' => 'App\\Entity\\reissuevoucher\\Voucher',
        ]);
    }
}
