<?php

namespace Container0TVwF8T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QrnShc5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qrnShc5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qrnShc5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'video' => ['privates', '.errored..service_locator.qrnShc5.App\\Entity\\trainingvideos\\Video', NULL, 'Cannot autowire service ".service_locator.qrnShc5": it references class "App\\Entity\\trainingvideos\\Video" but no such service exists.'],
            'videoRepository' => ['privates', 'App\\Repository\\trainingvideos\\VideoRepository', 'getVideoRepositoryService', true],
        ], [
            'video' => 'App\\Entity\\trainingvideos\\Video',
            'videoRepository' => 'App\\Repository\\trainingvideos\\VideoRepository',
        ]);
    }
}
