<?php

namespace ContainerM3XhPPN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3uqpK_F.App\Entity\trainingvideos\Category' shared service.
     *
     * @return \App\Entity\trainingvideos\Category
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3uqpK_F": it references class "App\\Entity\\trainingvideos\\Category" but no such service exists.');
    }
}
