<?php

namespace ContainerB3WO5h8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoucherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Tc3bGFc.App\Entity\Voucher' shared service.
     *
     * @return \App\Entity\Voucher
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Tc3bGFc": it references class "App\\Entity\\Voucher" but no such service exists.');
    }
}
