<?php

namespace ContainerSnIxYbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S_QsbceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s.Qsbce' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s.Qsbce'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\VoucherController::delete' => ['privates', '.service_locator.jStmmMc', 'get_ServiceLocator_JStmmMcService', true],
            'App\\Controller\\VoucherController::edit' => ['privates', '.service_locator.jStmmMc', 'get_ServiceLocator_JStmmMcService', true],
            'App\\Controller\\VoucherController::index' => ['privates', '.service_locator.ztv7FYg', 'get_ServiceLocator_Ztv7FYgService', true],
            'App\\Controller\\VoucherController::new' => ['privates', '.service_locator.RxoADQi', 'get_ServiceLocator_RxoADQiService', true],
            'App\\Controller\\VoucherController::search' => ['privates', '.service_locator.ztv7FYg', 'get_ServiceLocator_Ztv7FYgService', true],
            'App\\Controller\\VoucherController::show' => ['privates', '.service_locator.Tc3bGFc', 'get_ServiceLocator_Tc3bGFcService', true],
            'App\\Controller\\VoucherController::showShoesByStatus' => ['privates', '.service_locator.ztv7FYg', 'get_ServiceLocator_Ztv7FYgService', true],
            'App\\Controller\\VoucherController::updateStatus' => ['privates', '.service_locator.eyfOthP', 'get_ServiceLocator_EyfOthPService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\VoucherController:delete' => ['privates', '.service_locator.jStmmMc', 'get_ServiceLocator_JStmmMcService', true],
            'App\\Controller\\VoucherController:edit' => ['privates', '.service_locator.jStmmMc', 'get_ServiceLocator_JStmmMcService', true],
            'App\\Controller\\VoucherController:index' => ['privates', '.service_locator.ztv7FYg', 'get_ServiceLocator_Ztv7FYgService', true],
            'App\\Controller\\VoucherController:new' => ['privates', '.service_locator.RxoADQi', 'get_ServiceLocator_RxoADQiService', true],
            'App\\Controller\\VoucherController:search' => ['privates', '.service_locator.ztv7FYg', 'get_ServiceLocator_Ztv7FYgService', true],
            'App\\Controller\\VoucherController:show' => ['privates', '.service_locator.Tc3bGFc', 'get_ServiceLocator_Tc3bGFcService', true],
            'App\\Controller\\VoucherController:showShoesByStatus' => ['privates', '.service_locator.ztv7FYg', 'get_ServiceLocator_Ztv7FYgService', true],
            'App\\Controller\\VoucherController:updateStatus' => ['privates', '.service_locator.eyfOthP', 'get_ServiceLocator_EyfOthPService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VoucherController::delete' => '?',
            'App\\Controller\\VoucherController::edit' => '?',
            'App\\Controller\\VoucherController::index' => '?',
            'App\\Controller\\VoucherController::new' => '?',
            'App\\Controller\\VoucherController::search' => '?',
            'App\\Controller\\VoucherController::show' => '?',
            'App\\Controller\\VoucherController::showShoesByStatus' => '?',
            'App\\Controller\\VoucherController::updateStatus' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VoucherController:delete' => '?',
            'App\\Controller\\VoucherController:edit' => '?',
            'App\\Controller\\VoucherController:index' => '?',
            'App\\Controller\\VoucherController:new' => '?',
            'App\\Controller\\VoucherController:search' => '?',
            'App\\Controller\\VoucherController:show' => '?',
            'App\\Controller\\VoucherController:showShoesByStatus' => '?',
            'App\\Controller\\VoucherController:updateStatus' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
