<?php

namespace ContainerNxvXtYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SELYCJ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SELYCJ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SELYCJ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\reissuevoucher\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\reissuevoucher\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::delete' => ['privates', '.service_locator.5pAjOGf', 'get_ServiceLocator_5pAjOGfService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::edit' => ['privates', '.service_locator.5pAjOGf', 'get_ServiceLocator_5pAjOGfService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::index' => ['privates', '.service_locator.qhJ5uJH', 'get_ServiceLocator_QhJ5uJHService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::new' => ['privates', '.service_locator.2PEbKYl', 'get_ServiceLocator_2PEbKYlService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::search' => ['privates', '.service_locator.qhJ5uJH', 'get_ServiceLocator_QhJ5uJHService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::show' => ['privates', '.service_locator.Jqd_se5', 'get_ServiceLocator_JqdSe5Service', true],
            'App\\Controller\\reissuevoucher\\VoucherController::showShoesByStatus' => ['privates', '.service_locator.qhJ5uJH', 'get_ServiceLocator_QhJ5uJHService', true],
            'App\\Controller\\reissuevoucher\\VoucherController::updateStatus' => ['privates', '.service_locator.fZ_fM5A', 'get_ServiceLocator_FZFM5AService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\reissuevoucher\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\reissuevoucher\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:delete' => ['privates', '.service_locator.5pAjOGf', 'get_ServiceLocator_5pAjOGfService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:edit' => ['privates', '.service_locator.5pAjOGf', 'get_ServiceLocator_5pAjOGfService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:index' => ['privates', '.service_locator.qhJ5uJH', 'get_ServiceLocator_QhJ5uJHService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:new' => ['privates', '.service_locator.2PEbKYl', 'get_ServiceLocator_2PEbKYlService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:search' => ['privates', '.service_locator.qhJ5uJH', 'get_ServiceLocator_QhJ5uJHService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:show' => ['privates', '.service_locator.Jqd_se5', 'get_ServiceLocator_JqdSe5Service', true],
            'App\\Controller\\reissuevoucher\\VoucherController:showShoesByStatus' => ['privates', '.service_locator.qhJ5uJH', 'get_ServiceLocator_QhJ5uJHService', true],
            'App\\Controller\\reissuevoucher\\VoucherController:updateStatus' => ['privates', '.service_locator.fZ_fM5A', 'get_ServiceLocator_FZFM5AService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\reissuevoucher\\RegistrationController::register' => '?',
            'App\\Controller\\reissuevoucher\\SecurityController::login' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::delete' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::edit' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::index' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::new' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::search' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::show' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::showShoesByStatus' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController::updateStatus' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\reissuevoucher\\RegistrationController:register' => '?',
            'App\\Controller\\reissuevoucher\\SecurityController:login' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:delete' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:edit' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:index' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:new' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:search' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:show' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:showShoesByStatus' => '?',
            'App\\Controller\\reissuevoucher\\VoucherController:updateStatus' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
