<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSnIxYbb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSnIxYbb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSnIxYbb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSnIxYbb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSnIxYbb\App_KernelDevDebugContainer([
    'container.build_hash' => 'SnIxYbb',
    'container.build_id' => 'aec8c946',
    'container.build_time' => 1707329924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSnIxYbb');
