<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMuua5Od\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMuua5Od/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMuua5Od.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMuua5Od\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMuua5Od\App_KernelDevDebugContainer([
    'container.build_hash' => 'Muua5Od',
    'container.build_id' => '505f5445',
    'container.build_time' => 1708774900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMuua5Od');
