<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLABvoN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLABvoN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLABvoN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLABvoN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZLABvoN\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZLABvoN',
    'container.build_id' => '6c0079e4',
    'container.build_time' => 1707553663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLABvoN');
