<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'voucher_app_register' => [[], ['_controller' => 'App\\Controller\\reissuevoucher\\RegistrationController::register'], [], [['text', '/reissuevoucher/register']], [], [], []],
    'voucher_app_login' => [[], ['_controller' => 'App\\Controller\\reissuevoucher\\SecurityController::login'], [], [['text', '/reissuevoucher/login']], [], [], []],
    'voucher_app_logout' => [[], ['_controller' => 'App\\Controller\\reissuevoucher\\SecurityController::logout'], [], [['text', '/reissuevoucher/logout']], [], [], []],
    'app_voucher_index' => [[], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::index'], [], [['text', '/reissuevoucher/voucher']], [], [], []],
    'app_voucher_new' => [[], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::new'], [], [['text', '/reissuevoucher/voucher/form']], [], [], []],
    'app_voucher_search' => [[], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::search'], [], [['text', '/reissuevoucher/voucher/search']], [], [], []],
    'app_voucher_show' => [['id'], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reissuevoucher/voucher']], [], [], []],
    'app_voucher_edit' => [['id'], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reissuevoucher/voucher']], [], [], []],
    'app_voucher_delete' => [['id'], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reissuevoucher/voucher']], [], [], []],
    'voucher_update_status' => [['status', 'id'], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::updateStatus'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'status', true], ['text', '/reissuevoucher/voucher/update']], [], [], []],
    'voucher_dashboard_status' => [['status'], ['_controller' => 'App\\Controller\\reissuevoucher\\Voucher_reissueController::showVoucherReissueByStatus'], [], [['variable', '/', '[^/]++', 'status', true], ['text', '/reissuevoucher/voucher/update']], [], [], []],
    'app_video_index' => [[], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::index'], [], [['text', '/trainingvideos/videos']], [], [], []],
    'app_video_search' => [[], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::search'], [], [['text', '/trainingvideos/video']], [], [], []],
    'video_update_status' => [['status', 'id'], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::updateStatus'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'status', true], ['text', '/trainingvideos/video/update']], [], [], []],
    'app_video_new' => [[], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::new'], [], [['text', '/trainingvideos/video/form']], [], [], []],
    'app_video_edit' => [['id'], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/trainingvideos/video']], [], [], []],
    'app_video_delete' => [['id'], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/trainingvideos/video']], [], [], []],
    'video_dashboard_category' => [['category_id'], ['_controller' => 'App\\Controller\\trainingvideos\\VideoController::showShoesByStatus'], [], [['variable', '/', '[^/]++', 'category_id', true], ['text', '/trainingvideos/video/update']], [], [], []],
    'video_app_category_index' => [[], ['_controller' => 'App\\Controller\\trainingvideos\\CategoryController::index'], [], [['text', '/trainingvideos/category']], [], [], []],
    'video_app_category_new' => [[], ['_controller' => 'App\\Controller\\trainingvideos\\CategoryController::new'], [], [['text', '/trainingvideos/category/new']], [], [], []],
    'video_app_category_show' => [['id'], ['_controller' => 'App\\Controller\\trainingvideos\\CategoryController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/trainingvideos/category']], [], [], []],
    'video_app_category_edit' => [['id'], ['_controller' => 'App\\Controller\\trainingvideos\\CategoryController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/trainingvideos/category']], [], [], []],
    'video_app_category_delete' => [['id'], ['_controller' => 'App\\Controller\\trainingvideos\\CategoryController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/trainingvideos/category']], [], [], []],
];
